# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libreasr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="libreasr.proto",
    package="LibreASR",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0elibreasr.proto\x12\x08LibreASR"!\n\x05\x41udio\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\n\n\x02sr\x18\x02 \x01(\x05"\x1a\n\nTranscript\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x82\x01\n\x08LibreASR\x12\x35\n\nTranscribe\x12\x0f.LibreASR.Audio\x1a\x14.LibreASR.Transcript"\x00\x12?\n\x10TranscribeStream\x12\x0f.LibreASR.Audio\x1a\x14.LibreASR.Transcript"\x00(\x01\x30\x01\x62\x06proto3',
)


_AUDIO = _descriptor.Descriptor(
    name="Audio",
    full_name="LibreASR.Audio",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="LibreASR.Audio.data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sr",
            full_name="LibreASR.Audio.sr",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=61,
)


_TRANSCRIPT = _descriptor.Descriptor(
    name="Transcript",
    full_name="LibreASR.Transcript",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="LibreASR.Transcript.data",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=63,
    serialized_end=89,
)

DESCRIPTOR.message_types_by_name["Audio"] = _AUDIO
DESCRIPTOR.message_types_by_name["Transcript"] = _TRANSCRIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Audio = _reflection.GeneratedProtocolMessageType(
    "Audio",
    (_message.Message,),
    {
        "DESCRIPTOR": _AUDIO,
        "__module__": "libreasr_pb2"
        # @@protoc_insertion_point(class_scope:LibreASR.Audio)
    },
)
_sym_db.RegisterMessage(Audio)

Transcript = _reflection.GeneratedProtocolMessageType(
    "Transcript",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRANSCRIPT,
        "__module__": "libreasr_pb2"
        # @@protoc_insertion_point(class_scope:LibreASR.Transcript)
    },
)
_sym_db.RegisterMessage(Transcript)


_LIBREASR = _descriptor.ServiceDescriptor(
    name="LibreASR",
    full_name="LibreASR.LibreASR",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=92,
    serialized_end=222,
    methods=[
        _descriptor.MethodDescriptor(
            name="Transcribe",
            full_name="LibreASR.LibreASR.Transcribe",
            index=0,
            containing_service=None,
            input_type=_AUDIO,
            output_type=_TRANSCRIPT,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="TranscribeStream",
            full_name="LibreASR.LibreASR.TranscribeStream",
            index=1,
            containing_service=None,
            input_type=_AUDIO,
            output_type=_TRANSCRIPT,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_LIBREASR)

DESCRIPTOR.services_by_name["LibreASR"] = _LIBREASR

# @@protoc_insertion_point(module_scope)
