apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreasr
spec:
  selector:
    matchLabels:
      app: libreasr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: libreasr
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - image: libreasr-deploy:latest
        imagePullPolicy: Never
        name: libreasr
        env:
        - name: NUMBA_CACHE_DIR
          value: "/tmp"
        - name: MPLCONFIGDIR
          value: "/tmp"
        command:
        - /bin/bash
        - -c
        - 'cd /workspace && make deploy'
        ports:
        - containerPort: 8080
          name: http
      hostname: libreasr
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: libreasr
  labels:
    app: libreasr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: libreasr

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-libreasr-new
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - libreasr.example.com
    secretName: tls-libreasr-new
  rules:
  - host: libreasr.example.com
    http:
      paths:
      - backend:
          serviceName: libreasr
          servicePort: 80
